# Generated by Django 5.0.1 on 2024-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='platform',
            field=models.CharField(default='webapp', max_length=100),
        ),
    ]
