# Generated by Django 5.0.1 on 2024-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
